<html>
  <head>
    <title>nose: When Plugins Fail</title>
    <link rel="stylesheet" href="site.css" type="text/css"></link>
  </head>
  <body>
    
    <div id="menu">
      <p>This document covers nose version <b>0.11.0</b></p>
      <p>Last update: <b>Mon Sep  1 12:17:45 2008</b></p>
      <h2>Plugins</h2><ul><li><a href="plugin_attrib.html">Builtin Plugin: attrib</a></li><li><a href="plugin_capture.html">Builtin Plugin: capture</a></li><li><a href="plugin_cover.html">Builtin Plugin: cover</a></li><li><a href="plugin_debug.html">Builtin Plugin: debug</a></li><li><a href="plugin_deprecated.html">Builtin Plugin: deprecated</a></li><li><a href="plugin_doctests.html">Builtin Plugin: doctests</a></li><li><a href="plugin_failuredetail.html">Builtin Plugin: failuredetail</a></li><li><a href="plugin_isolate.html">Builtin Plugin: isolate</a></li><li><a href="plugin_logcapture.html">Builtin Plugin: logcapture</a></li><li><a href="plugin_multiprocess.html">Builtin Plugin: multiprocess</a></li><li><a href="plugin_prof.html">Builtin Plugin: prof</a></li><li><a href="plugin_skip.html">Builtin Plugin: skip</a></li><li><a href="plugin_testid.html">Builtin Plugin: testid</a></li><li><a href="error_class_plugin.html">ErrorClass Plugins</a></li><li><a href="plugin_interface.html">Plugin Interface</a></li><li><a href="writing_plugins.html">Writing Plugins</a></li></ul><h2>Modules</h2><ul><li><a href="module_nose.case.html">Module: nose.case</a></li><li><a href="module_nose.commands.html">Module: nose.commands</a></li><li><a href="module_nose.config.html">Module: nose.config</a></li><li><a href="module_nose.core.html">Module: nose.core</a></li><li><a href="module_nose.exc.html">Module: nose.exc</a></li><li><a href="module_nose.failure.html">Module: nose.failure</a></li><li><a href="module_nose.importer.html">Module: nose.importer</a></li><li><a href="module_nose.inspector.html">Module: nose.inspector</a></li><li><a href="module_nose.loader.html">Module: nose.loader</a></li><li><a href="module_nose.plugins.manager.html">Module: nose.plugins.manager</a></li><li><a href="module_nose.plugins.plugintest.html">Module: nose.plugins.plugintest</a></li><li><a href="module_nose.proxy.html">Module: nose.proxy</a></li><li><a href="module_nose.result.html">Module: nose.result</a></li><li><a href="module_nose.selector.html">Module: nose.selector</a></li><li><a href="module_nose.suite.html">Module: nose.suite</a></li><li><a href="module_nose.tools.html">Module: nose.tools</a></li><li><a href="module_nose.twistedtools.html">Module: nose.twistedtools</a></li><li><a href="module_nose.util.html">Module: nose.util</a></li></ul><h2>Plugin Examples</h2><ul><li><a href="doctest_fixtures.html">Doctest Fixtures</a></li><li><a href="unwanted_package.html">Excluding Unwanted Packages</a></li><li><a href="errorclass_failure.html">Failure of Errorclasses</a></li><li><a href="imported_tests.html">Importing Tests</a></li><li><a href="empty_plugin.html">Minimal plugin</a></li><li><a href="multiprocess.html">Parallel Testing with nose</a></li><li><a href="restricted_plugin_options.html">Restricted Plugin Managers</a></li><li><a href="init_plugin.html">Running Initialization Code Before the Test Run</a></li><li><a href="selector_plugin.html">Using a Custom Selector</a></li><li><a href="plugin_exceptions.html">When Plugins Fail</a></li><li><a href="plugintest_environment.html">nose.plugins.plugintest, os.environ and sys.argv</a></li></ul>
      
    </div>
    
    <div id="main">
      <h1>nose: When Plugins Fail</h1>
      
      <p>Plugin methods should not fail silently. When a plugin method raises
an exception before or during the execution of a test, the exception
will be wrapped in a <a class="reference" href="module_nose.failure.html#Failure">nose.failure.Failure</a> instance and appear as a
failing test. Exceptions raised at other times, such as in the
preparation phase with <tt class="docutils literal"><span class="pre">prepareTestLoader</span></tt> or <tt class="docutils literal"><span class="pre">prepareTestResult</span></tt>,
or after a test executes, in <tt class="docutils literal"><span class="pre">afterTest</span></tt> will stop the entire test
run.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">import</span> <span class="nn">os</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">import</span> <span class="nn">sys</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">from</span> <span class="nn">nose.plugins</span> <span class="k">import</span> <span class="n">Plugin</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">from</span> <span class="nn">nose.plugins.plugintest</span> <span class="k">import</span> <span class="n">run_buffered</span> <span class="k">as</span> <span class="n">run</span>
</pre></div>
</blockquote>
<p>Our first test plugins take no command-line arguments and raises
AttributeError in beforeTest and afterTest.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">EnabledPlugin</span><span class="p">(</span><span class="n">Plugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="sd">&quot;&quot;&quot;Plugin that takes no command-line arguments&quot;&quot;&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="n">enabled</span> <span class="o">=</span> <span class="bp">True</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">configure</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">options</span><span class="p">,</span> <span class="n">conf</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">pass</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">options</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">parser</span><span class="p">,</span> <span class="n">env</span><span class="o">=</span><span class="p">{}):</span>
<span class="gp">... </span>        <span class="k">pass</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">FailBeforePlugin</span><span class="p">(</span><span class="n">EnabledPlugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="n">name</span> <span class="o">=</span> <span class="s">&quot;fail-before&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">beforeTest</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">test</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">AttributeError</span><span class="p">()</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">FailAfterPlugin</span><span class="p">(</span><span class="n">EnabledPlugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="n">name</span> <span class="o">=</span> <span class="s">&quot;fail-after&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">afterTest</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">test</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">AttributeError</span><span class="p">()</span>
</pre></div>
</blockquote>
<p>Running tests with the fail-before plugin enabled will result in all
tests failing.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">support</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">dirname</span><span class="p">(</span><span class="n">__file__</span><span class="p">),</span> <span class="s">&#39;support&#39;</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">suitepath</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">support</span><span class="p">,</span> <span class="s">&#39;test_spam.py&#39;</span><span class="p">)</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">run</span><span class="p">(</span><span class="n">argv</span><span class="o">=</span><span class="p">[</span><span class="s">&#39;nosetests&#39;</span><span class="p">,</span> <span class="n">suitepath</span><span class="p">],</span>
<span class="gp">... </span>    <span class="n">plugins</span><span class="o">=</span><span class="p">[</span><span class="n">FailBeforePlugin</span><span class="p">()])</span>
<span class="go">EE</span>
<span class="go">======================================================================</span>
<span class="go">ERROR: test_spam.test_spam</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="gp">...</span>
<span class="go">AttributeError</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">======================================================================</span>
<span class="go">ERROR: test_spam.test_eggs</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="gp">...</span>
<span class="go">AttributeError</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="go">Ran 0 tests in ...s</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">FAILED (errors=2)</span>
</pre></div>
</blockquote>
<p>But with the fail-after plugin, the entire test run will fail.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">run</span><span class="p">(</span><span class="n">argv</span><span class="o">=</span><span class="p">[</span><span class="s">&#39;nosetests&#39;</span><span class="p">,</span> <span class="n">suitepath</span><span class="p">],</span>
<span class="gp">... </span>    <span class="n">plugins</span><span class="o">=</span><span class="p">[</span><span class="n">FailAfterPlugin</span><span class="p">()])</span>
<span class="gp">...</span>
<span class="go">AttributeError</span>
</pre></div>
</blockquote>
<p>Likewise since the next plugin fails in a preparatory method, outside
of test execution, the entire test run fails when the plugin is used.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">FailPreparationPlugin</span><span class="p">(</span><span class="n">EnabledPlugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="n">name</span> <span class="o">=</span> <span class="s">&quot;fail-prepare&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">prepareTestLoader</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">loader</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s">&quot;That loader is not my type&quot;</span><span class="p">)</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">run</span><span class="p">(</span><span class="n">argv</span><span class="o">=</span><span class="p">[</span><span class="s">&#39;nosetests&#39;</span><span class="p">,</span> <span class="n">suitepath</span><span class="p">],</span>
<span class="gp">... </span>    <span class="n">plugins</span><span class="o">=</span><span class="p">[</span><span class="n">FailPreparationPlugin</span><span class="p">()])</span>
<span class="gp">...</span>
<span class="go">TypeError: That loader is not my type</span>
</pre></div>
</blockquote>
<p>Even AttributeErrors and TypeErrors are not silently suppressed as
they used to be for some generative plugin methods (issueXXX).</p>
<p>These methods caught TypeError and AttributeError and did not record
the exception, before issue152 was fixed: .loadTestsFromDir(),
.loadTestsFromModule(), .loadTestsFromTestCase(),
loadTestsFromTestClass, and .makeTest().  Now, the exception is
caught, but logged as a Failure.</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">FailLoadPlugin</span><span class="p">(</span><span class="n">EnabledPlugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="n">name</span> <span class="o">=</span> <span class="s">&quot;fail-load&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">loadTestsFromModule</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">module</span><span class="p">):</span>
<span class="gp">... </span>        <span class="c"># we&#39;re testing exception handling behaviour during</span>
<span class="gp">... </span>        <span class="c"># iteration, so be a generator function, without</span>
<span class="gp">... </span>        <span class="c"># actually yielding any tests</span>
<span class="gp">... </span>        <span class="k">if</span> <span class="bp">False</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">yield</span> <span class="bp">None</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s">&quot;bug in plugin&quot;</span><span class="p">)</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">run</span><span class="p">(</span><span class="n">argv</span><span class="o">=</span><span class="p">[</span><span class="s">&#39;nosetests&#39;</span><span class="p">,</span> <span class="n">suitepath</span><span class="p">],</span>
<span class="gp">... </span>    <span class="n">plugins</span><span class="o">=</span><span class="p">[</span><span class="n">FailLoadPlugin</span><span class="p">()])</span>
<span class="go">..E</span>
<span class="go">======================================================================</span>
<span class="go">ERROR: Failure: TypeError (bug in plugin)</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="gp">...</span>
<span class="go">TypeError: bug in plugin</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="go">Ran 3 tests in ...s</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">FAILED (errors=1)</span>
</pre></div>
</blockquote>
<p>Also, before issue152 was resolved, .loadTestsFromFile() and
.loadTestsFromName() didn't catch these errors at all, so the
following test would crash nose:</p>
<blockquote>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">FailLoadFromNamePlugin</span><span class="p">(</span><span class="n">EnabledPlugin</span><span class="p">):</span>
<span class="gp">... </span>    <span class="n">name</span> <span class="o">=</span> <span class="s">&quot;fail-load-from-name&quot;</span>
<span class="gp">...</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">loadTestsFromName</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">name</span><span class="p">,</span> <span class="n">module</span><span class="o">=</span><span class="bp">None</span><span class="p">,</span> <span class="n">importPath</span><span class="o">=</span><span class="bp">None</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">if</span> <span class="bp">False</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">yield</span> <span class="bp">None</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s">&quot;bug in plugin&quot;</span><span class="p">)</span>
</pre></div>
<div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">run</span><span class="p">(</span><span class="n">argv</span><span class="o">=</span><span class="p">[</span><span class="s">&#39;nosetests&#39;</span><span class="p">,</span> <span class="n">suitepath</span><span class="p">],</span>
<span class="gp">... </span>    <span class="n">plugins</span><span class="o">=</span><span class="p">[</span><span class="n">FailLoadFromNamePlugin</span><span class="p">()])</span>
<span class="go">E</span>
<span class="go">======================================================================</span>
<span class="go">ERROR: Failure: TypeError (bug in plugin)</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="gp">...</span>
<span class="go">TypeError: bug in plugin</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">----------------------------------------------------------------------</span>
<span class="go">Ran 1 test in ...s</span>
<span class="go">&lt;BLANKLINE&gt;</span>
<span class="go">FAILED (errors=1)</span>
</pre></div>
</blockquote>


    </div>
    <script src="http://www.google-analytics.com/urchin.js" 
	    type="text/javascript">
    </script>
    <script type="text/javascript">
      _uacct = "UA-2236166-1";
      urchinTracker();
    </script>
  </body>
</html>
  
